import { redirect } from "next/navigation";
import { auth } from "@/lib/auth/auth";
import { verificarSessaoValida } from "@/lib/auth/verificar-sessao";
import { listarFilaDoDia } from "@/services/flashcards";
import { listarErros } from "@/services/questoes/erros";
import { criarFlashcardAction, revisarFlashcardAction } from "./actions";
import { SugestoesFlashcard } from "./sugestoes";
export const dynamic = "force-dynamic";
export default async function Page() { const s = await auth(); if (!s || !(await verificarSessaoValida(s)) || s.user.role !== "aluno") redirect("/login"); const [fila, erros] = await Promise.all([listarFilaDoDia(s.user.id, new Date()), listarErros(s.user.id)]); return <main className="mx-auto max-w-3xl space-y-7 px-4 py-8 lg:px-8"><header><p className="text-sm text-muted-foreground">Revisão diária</p><h1 className="text-2xl font-bold">Flashcards</h1><p className="text-sm text-muted-foreground"><b>{fila.length}</b> pendente(s).</p></header><form action={criarFlashcardAction} className="space-y-3 rounded-xl border bg-card p-5"><h2 className="font-semibold">Criar cartão</h2><textarea name="pergunta" required placeholder="Pergunta" className="min-h-20 w-full rounded border bg-transparent p-3 text-sm"/><textarea name="resposta" required placeholder="Resposta" className="min-h-20 w-full rounded border bg-transparent p-3 text-sm"/><button className="rounded bg-primary px-4 py-2 text-sm text-primary-foreground">Adicionar</button></form><SugestoesFlashcard erros={erros.map(e => ({ questionId: e.question_id, pergunta: e.questao.enunciado ?? "Questão para revisar" }))}/><section className="space-y-3" aria-label="Fila de revisão">{fila.map(c => <details data-testid="flashcard" key={c.id} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-medium">{c.pergunta}</summary><p className="mt-4 whitespace-pre-wrap text-sm text-muted-foreground">{c.resposta}</p><div className="mt-4 flex gap-2">{[true, false].map(ok => <form key={String(ok)} action={revisarFlashcardAction}><input type="hidden" name="flashcard_id" value={c.id}/><input type="hidden" name="acertou" value={String(ok)}/><button className="rounded border px-3 py-2 text-sm">{ok ? "Acertei" : "Errei"}</button></form>)}</div></details>)}{!fila.length && <p className="text-sm text-muted-foreground">Tudo em dia.</p>}</section></main>; }
